### ISSUE TITLE
Problem starting container

### ISSUE THREAD

**Issue by caymann12** [Pavlinchen/Porkbun-DDNS-Docker#3]
This doesnot start. Logs show:

SyntaxError: unmatched ')'
  File "/porkbun/main.py", line 26
    fillCron(DOMAIN=os.environ['Domain']).replace('*', '"*"'))
                                                             ^

**Comment by Pavlinchen** [comment]
Thanks for reporting the issue!

You're correct.
I forgot to remove the closing bracket after refactoring.

Please try again either after the build is finished or build from source.

**Comment by Pavlinchen** [comment]
nvm - there seems to be a deeper problem, I'll look into that,

**Comment by caymann12** [comment]
Traceback (most recent call last):
  File "/porkbun/porkbun-ddns.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by Pavlinchen** [comment]
Yup, also got that.
I don't know, what happened, but there were a few things wrong.
It works for me now, could you also please retry?

**Comment by Pavlinchen** [comment]
nope - sorry. The build failed again... :/

I'll get back to you

**Comment by Pavlinchen** [comment]
Hi again @caymann12.
So it seems, there's a deeper issue with GitHub Actions and non-native building.

Please build the container from source, as the code itself works (on my machine).

Also I have built the image locally and pushed it to the docker registry, but I can't for sure say for how long this version will be up, because of testing.

**Comment by Pavlinchen** [comment]
So, there were a few general problems, which are fixed on my side now.
Unfortunately there also seems to be an issue with the Porkbun API. - I've contacted Support.

@caymann12 could you please verify the operation of the container on your side aswell?

**Comment by Pavlinchen** [comment]
SLR,
fixed by porkbun staff

I rebuilt the docker image so everything is fine again now.
Thanks for pointing it out! :)

**Comment by caymann12** [comment]
Thank you
